### ISSUE TITLE
 Error in prior$sigma.inv.gamma + crossprod(beta[use.cols, ]) :    non-conformable arrays

### ISSUE THREAD

**Issue by jonrobinson2** [matthewtyler/MultiScale#1]
Took a crack at using this package for a simple exercise and I can't get the model to run for a 2D model. I get the error message in the issue title.

I'm using some survey data I have that is 9 items all recoded into 1,-1, and NA for about 4k individuals. I am able to fit a 1D model, but get the same results from my 1 column gamma matrix for sparse or intercept solutions for it as well, which to me seems odd.

Thoughts on what I need to do here?

**Comment by matthewtyler** [comment]
Sorry to get back to this so late --- I have been away from the office a lot this month. Thank you for bringing this to my attention.

I tried to recreate the error but couldn't. Even if I make it so that all the cells in a row or column are missing the method still runs. Is there any more information you could give me about how the data is different from the example in the readme?

**Comment by jonrobinson2** [comment]
Not really sure. It was a survey with also no missing data. Am not familiar with the underlying methods enough to know about what's going on w/ this and the EM algo. I'll close, but just wanted to be a good citizen and pay it forward!
